apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-engine
  namespace: payment-platform
  labels:
    app: routing-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-engine
  template:
    metadata:
      labels:
        app: routing-engine
    spec:
      containers:
        - name: routing-engine
          image: payment-online/routing-engine:1.0.0
          ports:
            - containerPort: 8006
          env:
            - name: PORT
              value: "8006"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: routing-engine
  namespace: payment-platform
  labels:
    app: routing-engine
spec:
  selector:
    app: routing-engine
  ports:
    - port: 8006
      targetPort: 8006
  type: ClusterIP
