apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  namespace: payment-platform
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: payment-online/fraud-detection:1.0.0
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: OLLAMA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-platform-config
                  key: OLLAMA_BASE_URL
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: payment-platform
  labels:
    app: fraud-detection
spec:
  selector:
    app: fraud-detection
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
