global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["backend:8081"]

  - job_name: fraud-detection
    static_configs:
      - targets: ["fraud-detection:8001"]

  - job_name: risk-scoring
    static_configs:
      - targets: ["risk-scoring:8002"]

  - job_name: kyc-verification
    static_configs:
      - targets: ["kyc-verification:8003"]

  - job_name: chatbot
    static_configs:
      - targets: ["chatbot:8004"]

  - job_name: recommendation
    static_configs:
      - targets: ["recommendation:8005"]

  - job_name: routing-engine
    static_configs:
      - targets: ["routing-engine:8006"]
